### PR TITLE
optimize mongo query

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/38)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/38)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[lib/service/result-gather.js, line 146 at r2](https://reviewable.io/reviews/kube-hpc/monitor-server/38#-MXb5kgr6UCltSSPTNKn:-MXb5kgr6UCltSSPTNKo:bdn6tfk) ([raw file](https://github.com/kube-hpc/monitor-server/blob/9ff613daa5794952fdc45196df73d452ff8a6e6a/lib/service/result-gather.js#L146)):*
> ```JavaScript
>     //         return j;
>     //     });
>     // }
> ```

Do you need old code?

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/38)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[lib/service/result-gather.js, line 146 at r2](https://reviewable.io/reviews/kube-hpc/monitor-server/38#-MXb5kgr6UCltSSPTNKn:-MXb6h3wCjo8IFALqJxR:b-896fix) ([raw file](https://github.com/kube-hpc/monitor-server/blob/9ff613daa5794952fdc45196df73d452ff8a6e6a/lib/service/result-gather.js#L146)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Do you need old code?
</blockquote></details>

Done.

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/38)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[lib/service/result-gather.js, line 146 at r2](https://reviewable.io/reviews/kube-hpc/monitor-server/38#-MXb5kgr6UCltSSPTNKn:-MXb6x4D1eabSJm_UoDK:b-896fix) ([raw file](https://github.com/kube-hpc/monitor-server/blob/9ff613daa5794952fdc45196df73d452ff8a6e6a/lib/service/result-gather.js#L146)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/38#-:-MXbOdUnECJUScZ5F_nw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
