### PR TITLE
add endpoint for original flow input

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/34)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/34)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[lib/service/etcd-data.js, line 109 at r1](https://reviewable.io/reviews/kube-hpc/monitor-server/34#-MShb2mz8r5rSi-dlrHM:-MShb2n-Bt4FHgPfFWEA:b69giy3) ([raw file](https://github.com/kube-hpc/monitor-server/blob/9a23adcc17d3844ccbe0af675c913237b26886d6/lib/service/etcd-data.js#L109)):*
> ```
> this._db.jobs.fetch
> ```

1) `fetch` only get `jobId`.
2) you can use `fetchAll` with these params but it will return an array....
3) if `fetch` like you did was working you couldn't do `job?.pipeline`, but `job?.userPipeline`, because you requested only the `userPipeline` and you don't need to do `key: 'jobId'`.
4) just do `const pipeline = await fetchPipeline ({ jobId });`

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/34)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[lib/service/etcd-data.js, line 109 at r1](https://reviewable.io/reviews/kube-hpc/monitor-server/34#-MShb2mz8r5rSi-dlrHM:-MShkwIq6VGKMNxSgduY:b-896fix) ([raw file](https://github.com/kube-hpc/monitor-server/blob/9a23adcc17d3844ccbe0af675c913237b26886d6/lib/service/etcd-data.js#L109)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> this._db.jobs.fetch
> ```

1) `fetch` only get `jobId`.
2) you can use `fetchAll` with these params but it will return an array....
3) if `fetch` like you did was working you couldn't do `job?.pipeline`, but `job?.userPipeline`, because you requested only the `userPipeline` and you don't need to do `key: 'jobId'`.
4) just do `const pipeline = await fetchPipeline ({ jobId });`

</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/34)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[lib/service/etcd-data.js, line 110 at r2](https://reviewable.io/reviews/kube-hpc/monitor-server/34#-MShlIay-7xwgXj4sxZM:-MShlIay-7xwgXj4sxZN:bljbhct) ([raw file](https://github.com/kube-hpc/monitor-server/blob/d68bf6e2eb2364ba180abbfa45fd0a82d85275ba/lib/service/etcd-data.js#L110)):*
> ```
>  return job?.pipeline.flowInput;
> ```
need to be pipeline?.flowInput

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/34#-:-MShlq_6DC1iTtBJiA45:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/34)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[lib/service/etcd-data.js, line 110 at r2](https://reviewable.io/reviews/kube-hpc/monitor-server/34#-MShlIay-7xwgXj4sxZM:-MShleLn0HwzawAtiiXg:b-896fix) ([raw file](https://github.com/kube-hpc/monitor-server/blob/d68bf6e2eb2364ba180abbfa45fd0a82d85275ba/lib/service/etcd-data.js#L110)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  return job?.pipeline.flowInput;
> ```
need to be pipeline?.flowInput
</blockquote></details>

Done.

**Pull request merged**
