### PR TITLE
feat: add disk usage

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/23)

### CODE REVIEW

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/23#-:-MH6v-ug-aGrswaFi7ib:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/23)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[lib/node-statistics/statistics.js, line 146 at r2](https://reviewable.io/reviews/kube-hpc/monitor-server/23#-MH6w03U7Bj--jrW7t5i:-MH6w03V1qLQ5599rIET:b2zt1jq) ([raw file](https://github.com/kube-hpc/monitor-server/blob/4c49058764eb49e46122558223638b531e8a58ef/lib/node-statistics/statistics.js#L146)):*
> ```JavaScript
>                 const usedP = parseFloat((1 - ratio).toFixed(2)) * 100;
>                 const freeP = parseFloat((ratio).toFixed(2)) * 100;
>                 const sizeH = prettyBytes(size);
> ```

why not do it in the UI? send just the raw usage?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/23)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[lib/node-statistics/statistics.js, line 146 at r2](https://reviewable.io/reviews/kube-hpc/monitor-server/23#-MH6w03U7Bj--jrW7t5i:-MH6zGcaDR5nkK65I9ed:b-896fix) ([raw file](https://github.com/kube-hpc/monitor-server/blob/4c49058764eb49e46122558223638b531e8a58ef/lib/node-statistics/statistics.js#L146)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why not do it in the UI? send just the raw usage?
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/monitor-server/23#-:-MHAPy7a2X34SMDheCLM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
